# Generated by Django 4.1 on 2022-12-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Commessa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField(unique=True)),
                ("data", models.DateField()),
                (
                    "valore",
                    models.DecimalField(
                        decimal_places=2, help_text="Valore IVA inclusa", max_digits=10
                    ),
                ),
                (
                    "valore_excluded",
                    models.DecimalField(
                        decimal_places=2, help_text="Valore IVA esclusa", max_digits=10
                    ),
                ),
                ("nota_valore", models.TextField(blank=True, default="")),
                (
                    "totale_valore",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Imponibile + IVA"
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=32)),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="PagamentoCommessa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "imponibile",
                    models.DecimalField(
                        decimal_places=2, help_text="Importo senza IVA", max_digits=10
                    ),
                ),
                (
                    "imponibile_ivato",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Imponibile + IVA"
                    ),
                ),
                ("nome", models.CharField(max_length=64)),
                (
                    "commessa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagamenti_commessa",
                        to="registry.commessa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Integrazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("importo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("nota", models.TextField()),
                (
                    "commessa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.commessa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sottocommessa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=64)),
                (
                    "commessa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sottocommesse",
                        to="registry.commessa",
                    ),
                ),
            ],
            options={
                "unique_together": {("commessa", "nome")},
            },
        ),
    ]
