# Generated by Django 4.1 on 2022-12-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornitore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="integrazione",
            name="nota",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="Costo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descrizione", models.TextField()),
                ("data", models.DateField()),
                ("fattura", models.CharField(max_length=128)),
                ("scadenza_pagamento", models.DateField()),
                ("tipo_pagamento", models.CharField(max_length=64)),
                (
                    "fornitore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.fornitore",
                    ),
                ),
                (
                    "sottocommessa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="registry.sottocommessa",
                    ),
                ),
            ],
        ),
    ]
